name: pipeline-deploy-s3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y pandoc

      # - run: pandoc README.md -f markdown -t html -s -o index.html
      - name: Cria index.html personalizado
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <title>Bem-vindo ao Meu Site!</title>
              <style>
                body { font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 40px; }
                h1 { color: #2c3e50; }
              </style>
          </head>
          <body>
              <h1>Deploy via GitHub Actions para S3 funcionando! 🚀</h1>
              <p>Este arquivo foi gerado automaticamente e enviado para o bucket <strong>${{ secrets.BUCKET_S3 }}</strong>.</p>
              <p><em>Última atualização: $(date)</em></p>
          </body>
          </html>
          EOF

            - run: ls -la

            - uses: actions/upload-artifact@v4
              with:
                name: site
                path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Puc
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: ${{ secrets.BUCKET_S3 }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: .

      - run: ls -la

      - run: aws sts get-caller-identity

      - run: aws s3 cp index.html "s3://$BUCKET_S3/index.html" --acl public-read

