name: integracao-ecr-eb

on:
  push:
    branches: [ main ]
  # workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Puc
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      TAG: latest
      REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      MODULE_FULLNAME: ${{ secrets.PROJECT_NAME }}/${{ secrets.MODULE_NAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
          aws sts get-caller-identity

      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t $MODULE_FULLNAME:$TAG .

      - name: Tag Docker image
        run: |
          docker tag $MODULE_FULLNAME:$TAG $REGISTRY_URL/$MODULE_FULLNAME:$TAG

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY_URL

      - name: Push Docker image
        run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json

  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: ebconfig
  #        path: .
  #    - run: |
  #        sed -i='' "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" Dockerrun.aws.json
  #        sed -i='' "s/<PROJECT_NAME>/$PROJECT_NAME/" Dockerrun.aws.json
  #        sed -i='' "s/<MODULE_NAME>/$MODULE_NAME/" Dockerrun.aws.json
  #        sed -i='' "s/<TAG>/$TAG/" Dockerrun.aws.json
  #    - uses: actions/setup-python@v3
  #      with:
  #        python-version: '3.10'
  #    - name: 'Install pip and awsebcli' #workaround: awsebcli não funciona com versões do pyyaml > 5.3
  #      run: |
  #          sudo wget https://bootstrap.pypa.io/get-pip.py  
  #
  #        sudo python3 ./get-pip.py
  #          sudo pip install "pyyaml<5.4"
  #          sudo pip install --upgrade setuptools
  #          sudo pip install --upgrade pip awsebcli            
  #    - run: |           
  #         eb deploy --verbose

    
