name: provisioning ecr-eb

on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}

jobs:
  provisioning:
    runs-on: ubuntu-latest
    environment: Puc
    env:
      TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      TF_VAR_MODULE_NAME: ${{ vars.MODULE_NAME }}
      TF_VAR_SOLUTION_STACK_NAME: ${{ vars.STACK_NAME }}
      TF_VAR_WORKING_DIR: ".environment"
      TF_VAR_PLAN_FILE: "planfile"
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR init

      - name: Terraform Plan
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR plan \
            -input=false -out=$TF_VAR_PLAN_FILE

      - name: Terraform Apply
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR apply \
            -auto-approve $TF_VAR_PLAN_FILE
