name: deploy_beanstalk

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # (outros steps como build/tag/push aqui...)

      # Upload dos arquivos necessários para deploy
      - uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      TAG: latest
    steps:
      - name: Baixar arquivos do build
        uses: actions/download-artifact@v4
        with:
          name: ebconfig
          path: .

      - name: Substituir variáveis no Dockerrun.aws.json
        run: |
          sed -i "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" Dockerrun.aws.json
          sed -i "s/<PROJECT_NAME>/$PROJECT_NAME/" Dockerrun.aws.json
          sed -i "s/<MODULE_NAME>/$MODULE_NAME/" Dockerrun.aws.json
          sed -i "s/<TAG>/$TAG/" Dockerrun.aws.json

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar awsebcli
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Fazer deploy com EB CLI
        run: eb deploy --verbose
