name: provisioning ecr-eb

on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  MODULE_NAME: ${{ secrets.MODULE_NAME }}

jobs:
  provisioning:
    runs-on: ubuntu-latest
    environment: Puc
    env:
      TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      TF_VAR_MODULE_NAME: ${{ secrets.MODULE_NAME }}
      TF_VAR_SOLUTION_STACK_NAME: ${{ secrets.STACK_NAME }}
      TF_VAR_WORKING_DIR: ".environment"
      TF_VAR_PLAN_FILE: "planfile"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug Variables (Opcional)
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "PROJECT_NAME: $PROJECT_NAME"
          echo "MODULE_NAME: $MODULE_NAME"
          echo "STACK_NAME: $TF_VAR_SOLUTION_STACK_NAME"

      - name: Terraform Init
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR init

      - name: Terraform Plan
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR plan \
            -input=false -out=$TF_VAR_PLAN_FILE

      - name: Terraform Apply
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR apply \
            -auto-approve $TF_VAR_PLAN_FILE
